export const SYSTEM_SYMPTOMS: Record<string, string[]> = {
  "General / Constitutional": ["Fever", "Weight loss (unintentional)", "Fatigue / Malaise", "Night sweats", "Loss of appetite", "Generalized weakness", "Chills / Rigors"],
  "Head & Neck": ["Headache", "Dizziness / Vertigo", "Neck stiffness", "Fainting / Syncope", "Scalp tenderness", "Neck swelling"],
  "Eyes / Vision": ["Blurred vision", "Double vision (Diplopia)", "Eye pain", "Redness", "Vision loss", "Photophobia", "Floaters", "Watery eyes"],
  "Ears / Hearing": ["Hearing loss", "Tinnitus (ringing)", "Ear pain (Otalgia)", "Ear discharge (Otorrhea)", "Vertigo", "Itching"],
  "Nose & Sinuses": ["Nasal congestion", "Nosebleeds (Epistaxis)", "Sinus pain / pressure", "Nasal discharge", "Loss of smell (Anosmia)", "Sneezing"],
  "Oral Cavity & Throat": ["Sore throat", "Difficulty swallowing (Dysphagia)", "Painful swallowing (Odynophagia)", "Hoarseness", "Oral ulcers", "Dental pain", "Gum bleeding", "Bad breath (Halitosis)", "Taste changes"],
  "Respiratory / Chest": ["Cough", "Shortness of breath (Dyspnea)", "Coughing up blood (Hemoptysis)", "Wheezing", "Sputum / Phlegm", "Chest pain (pleuritic)", "Night cough", "Orthopnea"],
  Cardiovascular: ["Chest pain (angina)", "Palpitations", "SOB on exertion", "Orthopnea", "PND", "Ankle swelling (Edema)", "Claudication", "Dizziness on standing"],
  "Gastrointestinal / Abdomen": ["Abdominal pain", "Nausea / Vomiting", "Diarrhea", "Constipation", "Vomiting blood (Hematemesis)", "Blood in stool (Melena / PR)", "Bloating / Distension", "Heartburn / Acid reflux", "Jaundice", "Change in bowel habit", "Early satiety"],
  Genitourinary: ["Painful urination (Dysuria)", "Blood in urine (Hematuria)", "Frequency", "Urgency", "Incontinence", "Flank pain", "Poor stream", "Nocturia"],
  Musculoskeletal: ["Joint pain (Arthralgia)", "Joint swelling", "Morning stiffness", "Muscle pain (Myalgia)", "Back pain", "Muscle weakness", "Bone pain", "Joint redness"],
  Neurological: ["Seizures / Convulsions", "Weakness (Paresis)", "Numbness / Tingling", "Tremor", "Loss of balance (Ataxia)", "Memory loss", "Speech difficulty (Dysarthria)", "Vision changes", "Loss of consciousness", "Difficulty walking"],
  "Skin / Dermatological": ["Rash", "Itching (Pruritus)", "Skin ulcers", "Lumps / Masses", "Change in mole", "Dryness (Xerosis)", "Hair loss (Alopecia)", "Nail changes", "Skin color changes"],
  "Endocrine / Metabolic": ["Heat intolerance", "Cold intolerance", "Excessive thirst (Polydipsia)", "Excessive urination (Polyuria)", "Goiter / Neck swelling", "Weight gain (unexplained)", "Excessive sweating", "Fatigue"],
  "Psychiatric / Psychological": ["Anxiety", "Depression / Low mood", "Sleep disturbance (Insomnia)", "Hallucinations", "Mood swings", "Loss of interest (Anhedonia)", "Memory / concentration problems", "Suicidal thoughts"],
  "Hematological / Lymphatic": ["Easy bruising", "Excessive bleeding", "Enlarged lymph nodes", "Pallor / Anemia symptoms", "Recurrent infections", "Night sweats", "Bone pain"],
  "Allergic / Immunological": ["Drug allergies", "Food allergies", "Skin rashes (Hives)", "Hay fever / Allergic rhinitis", "Asthma symptoms", "Recurrent infections"],
  Breast: ["Breast lump", "Breast pain (Mastalgia)", "Nipple discharge", "Nipple retraction", "Skin changes (Peau d'orange)", "Axillary lump", "Breast swelling"],
  "Gynecological / Obstetric": ["Abnormal vaginal bleeding", "Pelvic pain", "Vaginal discharge", "Painful periods (Dysmenorrhea)", "Missed periods (Amenorrhea)", "Heavy periods (Menorrhagia)", "Postmenopausal bleeding", "Pain during intercourse"],
};

export const ADL_CHOICES: { key: string; label: string }[] = [];
export const IADL_CHOICES: { key: string; label: string }[] = [];
export const CHARLSON_CHOICES: { key: string; label: string }[] = [];

/** ECOG Performance Status options — stable reference, avoids inline array recreation. */
export const ECOG_OPTIONS = [
  { value: "0", label: "0 — Fully active" },
  { value: "1", label: "1 — Restricted, ambulatory" },
  { value: "2", label: "2 — Ambulatory, capable of selfcare" },
  { value: "3", label: "3 — Limited selfcare, confined >50%" },
  { value: "4", label: "4 — Completely disabled" },
  { value: "5", label: "5 — Dead" },
] as const;

/** Charlson Comorbidity Index conditions — used for scoring widget. */
export const CHARLSON_CONDITIONS = [
  { label: "Myocardial infarction", weight: 1, key: "mi" },
  { label: "Congestive heart failure", weight: 1, key: "chf" },
  { label: "Peripheral vascular disease", weight: 1, key: "pvd" },
  { label: "Cerebrovascular disease", weight: 1, key: "cvd" },
  { label: "Dementia", weight: 1, key: "dementia" },
  { label: "Chronic pulmonary disease", weight: 1, key: "copd" },
  { label: "Connective tissue disease", weight: 1, key: "ctd" },
  { label: "Peptic ulcer disease", weight: 1, key: "pud" },
  { label: "Mild liver disease", weight: 1, key: "mld" },
  { label: "Diabetes (uncomplicated)", weight: 1, key: "dm_uncomplicated" },
  { label: "Diabetes (with complications)", weight: 2, key: "dm_complicated" },
  { label: "Hemiplegia / Paraplegia", weight: 2, key: "hemiplegia" },
  { label: "Moderate/severe renal disease", weight: 2, key: "renal" },
  { label: "Malignancy (without mets)", weight: 2, key: "malignancy" },
  { label: "Leukemia", weight: 2, key: "leukemia" },
  { label: "Lymphoma", weight: 2, key: "lymphoma" },
  { label: "Moderate/severe liver disease", weight: 3, key: "sld" },
  { label: "Metastatic solid tumor", weight: 6, key: "mets" },
  { label: "AIDS / HIV", weight: 6, key: "hiv" },
] as const;

export const TUMOUR_SITE_CATEGORIES: Record<string, string[]> = {
  "Head and Neck": [
    "Lip", "Tongue (Anterior 2/3)", "Base of Tongue", "Salivary Gland (Parotid)",
    "Salivary Gland (Submandibular)", "Salivary Gland (Sublingual)", "Salivary Gland NOS",
    "Floor of Mouth", "Gum (Upper)", "Gum (Lower)", "Buccal Mucosa", "Hard Palate",
    "Soft Palate", "Palate NOS", "Retromolar Trigone", "Mouth NOS",
    "Tonsil", "Oropharynx (Anterior Wall)", "Oropharynx (Lateral Wall)",
    "Oropharynx (Posterior Wall)", "Oropharynx NOS", "Nasopharynx",
    "Pyriform Sinus", "Hypopharynx (Postcricoid)", "Hypopharynx NOS",
    "Pharynx NOS", "Nasal Cavity", "Middle Ear", "Maxillary Sinus",
    "Ethmoid Sinus", "Frontal Sinus", "Sphenoid Sinus", "Sinonasal NOS",
    "Larynx (Supraglottis)", "Larynx (Glottis)", "Larynx (Subglottis)",
    "Larynx NOS", "Hypopharynx",
  ],
  "Digestive System": [
    "Esophagus (Upper)", "Esophagus (Middle)", "Esophagus (Lower)",
    "Esophagus NOS", "Stomach (Cardia)", "Stomach (Fundus)", "Stomach (Body)",
    "Stomach (Antrum)", "Stomach (Pylorus)", "Stomach NOS",
    "Duodenum", "Jejunum", "Ileum", "Small Intestine NOS",
    "Appendix", "Cecum", "Ascending Colon", "Hepatic Flexure",
    "Transverse Colon", "Splenic Flexure", "Descending Colon",
    "Sigmoid Colon", "Colon NOS", "Rectosigmoid Junction",
    "Rectum", "Anus / Anal Canal", "Anorectum",
    "Liver / Hepatocellular", "Intrahepatic Bile Duct / Cholangiocarcinoma",
    "Gallbladder", "Extrahepatic Bile Duct", "Ampulla of Vater",
    "Pancreas (Head)", "Pancreas (Body)", "Pancreas (Tail)",
    "Pancreas (Uncinate)", "Pancreas NOS", "Digestive Tract NOS",
  ],
  "Respiratory / Thoracic": [
    "Trachea", "Lung (Main Bronchus)", "Lung (Upper Lobe)",
    "Lung (Middle Lobe)", "Lung (Lower Lobe)", "Lung / Bronchus NOS",
    "Pleura (Mesothelioma)", "Pleura NOS", "Thymus", "Mediastinum NOS",
    "Chest Wall", "Respiratory NOS",
  ],
  "Bone / Soft Tissue / Sarcoma": [
    "Bone / Skull", "Bone / Mandible", "Bone / Spine / Vertebra",
    "Bone / Ribs / Sternum", "Bone / Pelvis / Sacrum", "Bone / Scapula",
    "Bone / Upper Limb", "Bone / Lower Limb", "Bone / Joint NOS",
    "Soft Tissue (Head/Neck)", "Soft Tissue (Trunk)", "Soft Tissue (Upper Limb)",
    "Soft Tissue (Lower Limb)", "Soft Tissue (Retroperitoneum)",
    "Soft Tissue (Abdominal Wall)", "Soft Tissue NOS",
    "Kaposi Sarcoma",
  ],
  "Skin": [
    "Skin / Eyelid", "Skin / Ear / Pinna", "Skin / Lip (Non-SCC)",
    "Skin / Face", "Skin / Scalp / Neck", "Skin / Trunk",
    "Skin / Upper Limb", "Skin / Lower Limb", "Skin NOS",
    "Melanoma (Eyelid)", "Melanoma (Ear / Pinna)", "Melanoma (Lip)",
    "Melanoma (Face)", "Melanoma (Scalp / Neck)", "Melanoma (Trunk)",
    "Melanoma (Upper Limb)", "Melanoma (Lower Limb)", "Melanoma NOS",
    "Merkel Cell Carcinoma",
  ],
  "Breast": [
    "Breast (Right)", "Breast (Left)", "Breast (Bilateral)", "Breast NOS",
  ],
  "Female Genital": [
    "Cervix Uteri (Endocervix)", "Cervix Uteri (Exocervix)", "Cervix Uteri NOS",
    "Corpus Uteri / Endometrium", "Uterus (Myometrium)", "Uterus NOS",
    "Ovary (Right)", "Ovary (Left)", "Ovary (Bilateral)", "Ovary NOS",
    "Fallopian Tube", "Vagina", "Vulva", "Female Genital NOS",
  ],
  "Male Genital": [
    "Prostate", "Testis (Right)", "Testis (Left)", "Testis NOS",
    "Penis", "Scrotum", "Male Genital NOS",
  ],
  "Urinary System": [
    "Kidney (Renal Parenchyma)", "Renal Pelvis", "Kidney NOS",
    "Ureter", "Bladder (Trigone)", "Bladder (Dome)", "Bladder (Lateral Wall)",
    "Bladder NOS", "Urethra", "Urachus", "Urinary NOS",
  ],
  "Eye / CNS": [
    "Eye / Orbit", "Eye (Retinoblastoma)", "Eye (Uveal Melanoma)",
    "Eye / Lacrimal Gland", "Eye NOS", "Cerebral Meninges",
    "Spinal Meninges", "Meninges NOS",
    "Brain (Frontal Lobe)", "Brain (Temporal Lobe)", "Brain (Parietal Lobe)",
    "Brain (Occipital Lobe)", "Brain (Cerebellum)", "Brain (Brainstem)",
    "Brain (Ventricle)", "Brain NOS",
    "Spinal Cord", "Cauda Equina",
    "Optic Nerve / Cranial Nerves", "Pituitary Gland", "Pineal Gland",
    "Craniopharyngeal Duct", "Nervous System NOS",
  ],
  "Endocrine": [
    "Thyroid", "Parathyroid", "Adrenal Gland (Right)", "Adrenal Gland (Left)",
    "Adrenal Gland NOS", "Carotid Body / Paraganglion",
    "Endocrine NOS",
  ],
  "Lymphatic / Hematologic": [
    "Hodgkin Lymphoma (Nodal)", "Hodgkin Lymphoma (Extranodal)",
    "Non-Hodgkin Lymphoma (Nodal)", "Non-Hodgkin Lymphoma (Extranodal)",
    "Lymphoma NOS", "Leukemia (Lymphoid / ALL / CLL)",
    "Leukemia (Myeloid / AML / CML)", "Leukemia (Monocytic)",
    "Leukemia NOS", "Multiple Myeloma / Plasmacytoma",
    "Myeloproliferative Neoplasm (MPN)", "Myelodysplastic Syndrome (MDS)",
    "Myelodysplastic / Myeloproliferative Neoplasm (MDS/MPN)",
    "Histiocytic / Dendritic Cell Neoplasm",
    "Immunoproliferative Disease", "Hematologic NOS",
  ],
  "Unknown / Other": [
    "Unknown Primary / CUP", "Ill-Defined Site NOS",
    "Metastatic Site NOS", "Lymph Node (Primary Unknown)",
    "Other / Not Otherwise Specified",
  ],
};
